# 服务器相关配置
server:
  port: 8081 # 设置应用的端口号，避免使用常见的8080以防冲突
  servlet:
    context-path: /api # 设置应用的统一访问前缀，例如 /api/user/register

# Spring相关配置
spring:
  application:
    name: linknei-api # 应用名称
  # 数据库连接池配置
  datasource:
    # 【请修改】: 将下面的URL、用户名和密码替换成你自己的
    url: jdbc:mysql://localhost:3306/linknei_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root # 数据库用户名
    password: 123456 # 数据库密码
  # Flyway配置
  flyway:
    enabled: true # 启用Flyway
    locations: classpath:db/migration # 迁移脚本位置
    baseline-on-migrate: true # 如果数据库不是空的，自动执行基准迁移
    out-of-order: false # 是否允许无序执行
    validate-on-migrate: true # 迁移时是否校验
    table: flyway_schema_history # Flyway元数据表名
    # 如果需要清理数据库（开发环境可用，生产环境禁用）
    clean-disabled: true # 禁用clean操作，防止意外删除数据
  logging:
     level:
       org.flywaydb: DEBUG
# JWT配置
jwt:
  secret: Oe8H9XZ3x2NpDQfY9vTr5qK6sLm7oP3aUv1wMxB2zC3yD4fE5gF6hG7jH8kJ
  expiration: 86400000 # 24小时(毫秒)

# SpringDoc配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    tags-sorter: alpha # 按字母顺序排序标签
    operations-sorter: alpha # 按字母顺序排序操作
  # 包含的路径，限制文档只显示指定路径下的API
  paths-to-match: 
    - /auth/**
    - /user/**
    - /job-applications/**
    - /job-posts/**
    - /enterprises/**
    - /map/**

# MyBatis-Plus 相关配置
mybatis-plus:
  # Mapper XML文件的位置
  mapper-locations: classpath:/mapper/*.xml
  # 全局配置
  global-config:
    db-config:
      # 逻辑删除配置 (推荐实践)
      # 0代表未删除, 1代表已删除
      logic-delete-value: 1 # 逻辑已删除值(默认为1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为0)
  # 配置项
  configuration:
    # 开启驼峰命名转换：将数据库的 a_column 自动映射到实体的 aColumn 属性
    map-underscore-to-camel-case: true
    # 控制台打印SQL，方便开发调试
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl