# 服务器相关配置
server:
  port: 8081 # 设置应用的端口号，避免使用常见的8080以防冲突
  servlet:
    context-path: /api # 设置应用的统一访问前缀，例如 /api/user/register

# Spring相关配置
spring:
  application:
    name: unicorp-api # 应用名称
  # 数据库连接池配置
  datasource:
    # 【请修改】: 将下面的URL、用户名和密码替换成你自己的
    url: jdbc:mysql://localhost:3306/unicorp?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root # 数据库用户名
    password: 123456 # 数据库密码
  # 文件上传配置
  servlet:
    multipart:
      enabled: true # 启用文件上传
      max-file-size: 10MB # 单个文件最大大小
      max-request-size: 20MB # 单次请求最大大小
  # Flyway配置
  flyway:
    enabled: true # 启用Flyway
    locations: classpath:db/migration # 迁移脚本位置
    baseline-on-migrate: true # 如果数据库不是空的，自动执行基准迁移
    out-of-order: false # 是否允许无序执行
    validate-on-migrate: false # 临时禁用迁移验证，解决校验和问题
    table: flyway_schema_history # Flyway元数据表名
    # 如果需要清理数据库（开发环境可用，生产环境禁用）
    clean-disabled: true # 禁用clean操作，防止意外删除数据
    # 添加修复模式，自动修复校验错误
    repair: true
  logging:
    level:
      root: INFO
      com.csu.unicorp: INFO
      org.springframework.security: INFO
# JWT配置
jwt:
  secret: Oe8H9XZ3x2NpDQfY9vTr5qK6sLm7oP3aUv1wMxB2zC3yD4fE5gF6hG7jH8kJ
  expiration: 86400000 # 24小时(毫秒)

# 文件上传配置
file:
  upload-dir: upload # 文件上传目录
  base-url: http://localhost:8081/api/v1/files # 文件访问基础URL

# SpringDoc配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    tags-sorter: alpha # 按字母顺序排序标签
    operations-sorter: alpha # 按字母顺序排序操作
  # 包含的路径，限制文档只显示指定路径下的API
  paths-to-match:
    - /v1/auth/**
    - /v1/admin/**
    - /v1/school-admin/**
    - /v1/enterprise-admin/**
    - /v1/jobs/**
    - /v1/projects/**
    - /v1/organizations/**
    - /v1/map/**
    - /v1/applications/**
    - /v1/me/**
    - /v1/project-applications/**
    - /v1/resources/**
    - /v1/files/**
  # API分组配置
  group-configs:
    - group: "资源共享中心"
      paths-to-match:
        - /v1/resources/**
        - /v1/files/**
      display-name: "资源共享中心API"
      description: "包括资源的上传、浏览、管理和下载功能。"

# MyBatis-Plus 相关配置
mybatis-plus:
  # Mapper XML文件的位置
  mapper-locations: classpath:/mapper/*.xml
  # 全局配置
  global-config:
    db-config:
      # 逻辑删除配置 (推荐实践)
      # 0代表未删除, 1代表已删除
      logic-delete-field: is_deleted
      logic-delete-value: 1 # 逻辑已删除值(默认为1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为0)
  # 配置项
  configuration:
    # 开启驼峰命名转换：将数据库的 a_column 自动映射到实体的 aColumn 属性
    map-underscore-to-camel-case: true
    # 控制台打印SQL，方便开发调试
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
amap:
  key: "6ac0fa4484bd83396be5cf7440a806c3"