# 服务器相关配置
server:
  port: 8081 # 设置应用的端口号，避免使用常见的8080以防冲突
  servlet:
    context-path: /api # 设置应用的统一访问前缀，例如 /api/user/register

# Spring相关配置
spring:
  application:
    name: unicorp-api # 应用名称
  # 数据库连接池配置
  datasource:
    # 【请修改】: 将下面的URL、用户名和密码替换成你自己的
    url: jdbc:mysql://localhost:3306/unicorp?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root # 数据库用户名
    password: 123456 # 数据库密码
  # 文件上传配置
  servlet:
    multipart:
      enabled: true # 启用文件上传
      max-file-size: 10MB # 单个文件最大大小
      max-request-size: 20MB # 单次请求最大大小
  # Flyway配置
  flyway:
    enabled: true # 启用Flyway
    locations: classpath:db/migration # 迁移脚本位置
    baseline-on-migrate: true # 如果数据库不是空的，自动执行基准迁移
    out-of-order: false # 是否允许无序执行
    validate-on-migrate: false # 临时禁用迁移验证，解决校验和问题
    table: flyway_schema_history # Flyway元数据表名
    # 如果需要清理数据库（开发环境可用，生产环境禁用）
    clean-disabled: true # 禁用clean操作，防止意外删除数据
    # 添加修复模式，自动修复校验错误
    repair: true
  logging:
    level:
      root: INFO
      com.csu.unicorp: DEBUG  # 将应用代码日志级别设为DEBUG
      com.csu.unicorp.config.security: TRACE  # 安全配置相关日志设为TRACE
      org.springframework.security: DEBUG  # 安全相关日志设为DEBUG
      org.springframework.web: DEBUG  # Web相关日志设为DEBUG
      org.hibernate.SQL: DEBUG  # 显示SQL语句
      org.hibernate.type.descriptor.sql: TRACE  # 显示SQL参数绑定值
# JWT配置
jwt:
  secret: Oe8H9XZ3x2NpDQfY9vTr5qK6sLm7oP3aUv1wMxB2zC3yD4fE5gF6hG7jH8kJ
  expiration: 86400000 # 24小时(毫秒)

# 文件上传配置
app:
  upload:
    dir: upload
    max-size: 10485760  # 10MB
  base-url: http://localhost:8081

# SpringDoc配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  paths-to-match:
    - /v1/auth/**
    - /v1/admin/**
    - /v1/organizations/**
    - /v1/schools/**
    - /v1/enterprises/**
    - /v1/jobs/**
    - /v1/applications/**
    - /v1/files/**
    - /v1/students/**
    - /v1/teachers/**
    - /v1/mentors/**
  default-flat-param-object: true
  group-configs:
    - group: '认证与用户管理'
      paths-to-match: 
        - /v1/auth/**
        - /v1/admin/**
        - /v1/school-admin/**
        - /v1/enterprise-admin/**
        - /v1/profiles/**
        - /v1/me/**
      packages-to-scan: com.csu.unicorp.controller
    - group: '组织与机构管理'
      paths-to-match: 
        - /v1/organizations/**
      packages-to-scan: com.csu.unicorp.controller
    - group: '招聘与应聘'
      paths-to-match: 
        - /v1/jobs/**
        - /v1/applications/**
        - /v1/me/applications/**
      packages-to-scan: com.csu.unicorp.controller
    - group: '项目与合作'
      paths-to-match: 
        - /v1/projects/**
        - /v1/project-applications/**
      packages-to-scan: com.csu.unicorp.controller
    - group: '资源与文件'
      paths-to-match: 
        - /v1/resources/**
        - /v1/files/**
      packages-to-scan: com.csu.unicorp.controller
    - group: '个人作品集'
      paths-to-match: 
        - /v1/me/portfolio/**
      packages-to-scan: com.csu.unicorp.controller
    - group: '收藏功能'
      paths-to-match: 
        - /v1/me/favorites/**
        - /v1/jobs/*/favorite
      packages-to-scan: com.csu.unicorp.controller
    - group: '地图服务'
      paths-to-match: 
        - /v1/map/**
      packages-to-scan: com.csu.unicorp.controller

# MyBatis-Plus 相关配置
mybatis-plus:
  # Mapper XML文件的位置
  mapper-locations: classpath:/mapper/*.xml
  # 全局配置
  global-config:
    db-config:
      # 逻辑删除配置 (推荐实践)
      # 0代表未删除, 1代表已删除
      logic-delete-field: is_deleted
      logic-delete-value: 1 # 逻辑已删除值(默认为1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为0)
  # 配置项
  configuration:
    # 开启驼峰命名转换：将数据库的 a_column 自动映射到实体的 aColumn 属性
    map-underscore-to-camel-case: true
    # 控制台打印SQL，方便开发调试（设置为更详细的输出）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
amap:
  key: "6ac0fa4484bd83396be5cf7440a806c3"